-- ============================================================
-- Virtual Cadence — Supabase Schema (ANONYMOUS / NO-AUTH mode)
-- Run this in Supabase Dashboard → SQL Editor.
--
-- This converts the schema to a PUBLIC PROTOTYPE: anyone can
-- create projects/jobs, upload files, and read them WITHOUT
-- signing in. RLS is disabled and the storage bucket is public.
--
-- NOTE: this removes all per-user isolation. Do not use this
-- mode for production.
-- ============================================================

-- ---------- Drop existing auth-based RLS policies ----------
do $$
declare p record;
begin
  for p in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and policyname like '% own'
  loop
    execute format('drop policy if exists %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;

-- ---------- Tables (if not already created) ----------
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  user_id uuid,
  status text not null default 'CREATED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs (id) on delete cascade,
  user_id uuid,
  filename text not null,
  storage_path text not null,
  file_type text not null default 'other',
  file_size bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs (id) on delete cascade,
  user_id uuid,
  filename text not null,
  storage_path text not null,
  result_type text not null default 'report',
  created_at timestamptz not null default now()
);

-- human-readable since you may not want to expose the full numeric id to a job system
alter table public.projects alter column user_id drop not null;
alter table public.jobs alter column user_id drop not null;
alter table public.files alter column user_id drop not null;
alter table public.results alter column user_id drop not null;

-- ---------- Disable RLS (anonymous public prototype) ----------
alter table public.projects disable row level security;
alter table public.jobs disable row level security;
alter table public.files disable row level security;
alter table public.results disable row level security;

-- ---------- Storage (bucket: design-files) ----------
insert into storage.buckets (id, name, public)
values ('design-files', 'design-files', true)
on conflict (id) do update set public = true;

-- Drop the auth-based storage policies
drop policy if exists "design-files upload own" on storage.objects;
drop policy if exists "design-files read own" on storage.objects;
drop policy if exists "design-files update own" on storage.objects;
drop policy if exists "design-files delete own" on storage.objects;

-- Allow anyone (no login) to read/write files in the bucket
create policy "design-files public read" on storage.objects
  for select to public using (bucket_id = 'design-files');

create policy "design-files public insert" on storage.objects
  for insert to public with check (bucket_id = 'design-files');

create policy "design-files public update" on storage.objects
  for update to public using (bucket_id = 'design-files');

create policy "design-files public delete" on storage.objects
  for delete to public using (bucket_id = 'design-files');